
CREATE DATABASE BANHANG3

GO

USE BANHANG3

GO

------------------------------------------------------------------------TAO BANG

CREATE TABLE NHOMSP (MANHOM INT IDENTITY PRIMARY KEY, TENNHOM NVARCHAR(50))

GO

CREATE TABLE SANPHAM (IDSP INT IDENTITY PRIMARY KEY, 
MANHOM INT FOREIGN KEY (MANHOM) REFERENCES NHOMSP(MANHOM),
MASP NVARCHAR(20), TENSP NVARCHAR(50), DVT NVARCHAR(50), 
GIABAN DECIMAL(18,0), IMG NVARCHAR(255))

GO

CREATE TABLE NGUOIDUNG(ID INT IDENTITY, TENDANGNHAP VARCHAR(100) PRIMARY KEY, MATKHAU VARCHAR(100))
INSERT NGUOIDUNG (TENDANGNHAP, MATKHAU) 
VALUES ('nvdung', '123'), ('admin', '123')

GO

CREATE TABLE TRANGTHAI(ID INT IDENTITY, TENTRANGTHAI NVARCHAR(100) PRIMARY KEY)
INSERT TRANGTHAI (TENTRANGTHAI) 
VALUES (N'ĐANG CHUẨN BỊ HÀNG'), (N'ĐANG VẬN CHUYỆN'), (N'ĐANG GIAO HÀNG TỚI BẠN'), (N'GIAO HÀNG THÀNH CÔNG'), (N'Đã Nhận'), (N'LỖI')

GO

CREATE TABLE LOC (IDLOC INT IDENTITY PRIMARY KEY, TENLOC NVARCHAR(50))
GO
INSERT LOC (TENLOC) VALUES (N'LỌC THEO NGÀY'), (N'LỌC THEO THÁNG'), (N'LỌC THEO NĂM')

GO

CREATE TABLE DONHANG(IDDH INT IDENTITY PRIMARY KEY,
TENDANGNHAP VARCHAR(100) FOREIGN KEY (TENDANGNHAP) REFERENCES NGUOIDUNG(TENDANGNHAP), NGAYDATHANG DATE,
SOLUONGDH INT, TONGTIENDH DECIMAL(18,0), TRANGTHAIDH NVARCHAR(100) FOREIGN KEY (TRANGTHAIDH) REFERENCES TRANGTHAI(TENTRANGTHAI),
IDSP INT FOREIGN KEY (IDSP) REFERENCES SANPHAM(IDSP))

GO

CREATE TABLE KHOHANG(IDKHO INT IDENTITY PRIMARY KEY, 
IDSP INT FOREIGN KEY (IDSP) REFERENCES SANPHAM(IDSP), SOLUONGKHO INT, GIANHAPHANG DECIMAL(18, 0))


--------------------------------------------------------------------TAO PROC

GO

CREATE PROC usp_GetProducts(@MANHOM INT)
AS
BEGIN
		SELECT *, KH.SOLUONGKHO FROM NHOMSP AS N, SANPHAM AS S, KHOHANG AS KH WHERE N.MANHOM = S.MANHOM AND S.IDSP = KH.IDSP AND N.MANHOM = @MANHOM
END

GO

CREATE PROC usp_DelSanpham(@IDSP INT)
AS
BEGIN
	IF EXISTS(SELECT * FROM SANPHAM WHERE IDSP = @IDSP) BEGIN
		IF EXISTS(SELECT * FROM KHOHANG WHERE IDSP = @IDSP) BEGIN
			DELETE KHOHANG WHERE IDSP = @IDSP;
			DELETE SANPHAM WHERE IDSP = @IDSP;
		END ELSE BEGIN
						PRINT('IDSP KHONG TON TAI TRONG BANG SANPHAM')
					END
	END ELSE BEGIN
		PRINT('IDSP KHONG TON TAI TRONG BANG SANPHAM')
	END
END

GO

CREATE PROC usp_GetSanpham(@IDSP INT)
AS
BEGIN
	IF EXISTS(SELECT * FROM SANPHAM WHERE IDSP = @IDSP)BEGIN
		SELECT * FROM SANPHAM WHERE IDSP = @IDSP
	END ELSE BEGIN
		PRINT('IDSP KHONG TON TAI TRONG BANG SANPHAM')
	END
END

GO

CREATE PROC usp_UpdSanpham(@IMG NVARCHAR(255), @IDSP INT, @TENSP NVARCHAR(50), @MASP NVARCHAR(20), @DVT NVARCHAR(50), @GIABAN DECIMAL(18, 0), @MANHOM INT)
AS
BEGIN
	IF EXISTS (SELECT * FROM NHOMSP WHERE MANHOM = @MANHOM) BEGIN
		IF EXISTS (SELECT * FROM SANPHAM WHERE IDSP = @IDSP) BEGIN
			UPDATE SANPHAM SET IMG = @IMG, TENSP = @TENSP, MASP = @MASP, DVT = @DVT, GIABAN = @GIABAN, MANHOM = @MANHOM WHERE IDSP = @IDSP
		END
	END
END

GO

CREATE PROC usp_GetNhoms
AS
BEGIN
	SELECT TENNHOM, MANHOM FROM NHOMSP
END

GO

CREATE PROC usp_InsSanpham(@IMG NVARCHAR(255) ,@TENSP NVARCHAR(50), @MASP NVARCHAR(20), @DVT NVARCHAR(50), @GIABAN DECIMAL(18, 0), @MANHOM INT)
AS
BEGIN
	DECLARE @IDSP INT;
	IF NOT EXISTS(SELECT * FROM SANPHAM WHERE MASP = @MASP) BEGIN
		IF EXISTS(SELECT * FROM NHOMSP WHERE MANHOM = @MANHOM) BEGIN
			INSERT SANPHAM (TENSP, MASP, DVT, GIABAN, MANHOM, IMG) 
			VALUES (@TENSP, @MASP, @DVT, @GIABAN, @MANHOM, @IMG)

			SELECT @IDSP = IDSP FROM SANPHAM WHERE MASP = @MASP

			IF NOT EXISTS (SELECT * FROM KHOHANG WHERE IDSP = @IDSP) BEGIN
			INSERT KHOHANG (IDSP, SOLUONGKHO,GIANHAPHANG)
			VALUES (@IDSP, 0, 0)
			END
		END
	END
END

GO

CREATE PROC usp_InsNhomsanpham(@TENNHOM NVARCHAR(50))
AS
BEGIN
	INSERT NHOMSP (TENNHOM) VALUES (@TENNHOM)
END

GO

CREATE PROC usp_InsNguoidung(@TENDANGNHAP VARCHAR(100), @MATKHAU VARCHAR(100))
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE TENDANGNHAP = @TENDANGNHAP) BEGIN
		INSERT NGUOIDUNG (TENDANGNHAP, MATKHAU) VALUES (@TENDANGNHAP, @MATKHAU)
	END
END

GO

CREATE PROC usp_GetDONHANG(@TENDANGNHAP VARCHAR(100))
AS
BEGIN
	IF EXISTS(SELECT * FROM DONHANG WHERE TENDANGNHAP = @TENDANGNHAP) BEGIN
		SELECT DH.IDDH ,ND.TENDANGNHAP,SP.IMG, SP.TENSP, DH.SOLUONGDH, DH.TONGTIENDH, DH.TRANGTHAIDH 
		FROM NGUOIDUNG AS ND, SANPHAM AS SP, DONHANG AS DH 
		WHERE SP.IDSP = DH.IDSP AND DH.TENDANGNHAP = ND.TENDANGNHAP AND ND.TENDANGNHAP = @TENDANGNHAP ORDER BY DH.IDDH DESC
	END 
END

GO

CREATE PROC usp_InsDonhang(@TENDANGNHAP VARCHAR(100),@NGAY DATE, @SOLUONGDH INT, @TONGTIENDH DECIMAL(18, 0), @TRANGTHAIDH NVARCHAR(100), @IDSP INT)
AS
BEGIN
	DECLARE @IDKH INT, @SOLUONGTONKHO INT;
	SELECT @IDKH = IDKHO, @SOLUONGTONKHO = SOLUONGKHO FROM KHOHANG WHERE IDSP = @IDSP
	IF(@SOLUONGTONKHO >= @SOLUONGDH) BEGIN
	IF EXISTS(SELECT * FROM NGUOIDUNG WHERE TENDANGNHAP = @TENDANGNHAP) BEGIN
		IF EXISTS(SELECT * FROM SANPHAM AS SP, KHOHANG AS KH WHERE SP.IDSP = KH.IDSP AND SP.IDSP = @IDSP) BEGIN
			SELECT @IDKH = IDKHO FROM KHOHANG WHERE IDSP = @IDSP

			INSERT DONHANG (TENDANGNHAP,NGAYDATHANG, SOLUONGDH, TONGTIENDH, TRANGTHAIDH, IDSP) 
			VALUES (@TENDANGNHAP,@NGAY ,@SOLUONGDH, @TONGTIENDH, @TRANGTHAIDH ,@IDSP)

			UPDATE KHOHANG SET SOLUONGKHO = SOLUONGKHO - @SOLUONGDH WHERE IDKHO = @IDKH
			END
		END
	END
END

GO

CREATE PROC PROC_XOADONHANG(@IDDH INT)
AS
BEGIN
	DECLARE @IDKHO INT, @SOLUONG INT;
	IF EXISTS(SELECT * FROM DONHANG WHERE IDDH = @IDDH)BEGIN
		IF EXISTS(SELECT * FROM DONHANG WHERE TRANGTHAIDH = N'ĐANG CHUẨN BỊ HÀNG' AND IDDH = @IDDH) BEGIN

				SELECT @SOLUONG = DH.SOLUONGDH, @IDKHO = KH.IDKHO FROM DONHANG AS DH, KHOHANG AS KH WHERE DH.IDSP = KH.IDSP AND DH.IDDH = @IDDH
				
				UPDATE KHOHANG SET SOLUONGKHO = SOLUONGKHO + @SOLUONG WHERE IDKHO = @IDKHO

				DELETE DONHANG WHERE IDDH = @IDDH
		END 
	END
END

GO

CREATE PROC PROC_XACNHANDONHANG(@IDDH INT)
AS
BEGIN
	IF EXISTS(SELECT * FROM DONHANG WHERE IDDH = @IDDH) BEGIN
		IF EXISTS(SELECT * FROM DONHANG WHERE TRANGTHAIDH = N'GIAO HÀNG THÀNH CÔNG' AND IDDH = @IDDH) BEGIN
				UPDATE DONHANG SET TRANGTHAIDH = N'Đã Nhận' WHERE IDDH = @IDDH
		END
	END
END

SELECT * FROM DONHANG

GO

CREATE PROC usp_GetDONDATHANG
AS
BEGIN
	
		SELECT DH.IDDH ,ND.TENDANGNHAP,SP.IMG, SP.TENSP, DH.SOLUONGDH, DH.TONGTIENDH, DH.TRANGTHAIDH 
		FROM NGUOIDUNG AS ND, SANPHAM AS SP, DONHANG AS DH 
		WHERE SP.IDSP = DH.IDSP AND DH.TENDANGNHAP = ND.TENDANGNHAP ORDER BY DH.IDDH DESC
	 
END

GO

CREATE PROC usp_GetTrangthais
AS
BEGIN
	SELECT ID, TENTRANGTHAI FROM TRANGTHAI ORDER BY ID
END

GO

CREATE PROC usp_GetDONHANGTENTAIKHOAN(@IDDH INT)
AS
BEGIN
		SELECT DH.IDDH ,ND.TENDANGNHAP,SP.IMG, SP.TENSP, DH.SOLUONGDH, DH.TONGTIENDH, TT.ID 
		FROM NGUOIDUNG AS ND, SANPHAM AS SP, DONHANG AS DH, TRANGTHAI AS TT 
		WHERE SP.IDSP = DH.IDSP AND DH.TENDANGNHAP = ND.TENDANGNHAP AND DH.IDDH = @IDDH AND TT.TENTRANGTHAI = DH.TRANGTHAIDH
END

GO

GO

CREATE PROC THUCNGUYENDENVIMAY(@IDDH INT, @ID INT)
AS
BEGIN
	DECLARE @TENTRANGTHAI NVARCHAR(100)
	IF EXISTS(SELECT * FROM DONHANG WHERE IDDH = @IDDH) BEGIN
		IF EXISTS(SELECT * FROM TRANGTHAI WHERE ID = @ID) BEGIN
			SELECT @TENTRANGTHAI = TENTRANGTHAI FROM TRANGTHAI WHERE ID = @ID

			UPDATE DONHANG SET TRANGTHAIDH = @TENTRANGTHAI WHERE IDDH = @IDDH
		END
	END
END

GO

CREATE PROC usp_GetTrangthai
AS
BEGIN
	SELECT ID, TENTRANGTHAI FROM TRANGTHAI ORDER BY ID ASC
END

GO

CREATE PROC usp_GetDONDATHANGTHEOTRANGTHAI(@ID INT)
AS
BEGIN
	DECLARE @TENTRANGTHAI NVARCHAR(100);
	IF EXISTS (SELECT * FROM TRANGTHAI WHERE ID = @ID) BEGIN
	SELECT @TENTRANGTHAI = TENTRANGTHAI FROM TRANGTHAI WHERE ID = @ID

	SELECT DH.IDDH ,ND.TENDANGNHAP,SP.IMG, SP.TENSP, DH.SOLUONGDH, DH.TONGTIENDH, DH.TRANGTHAIDH 
		FROM NGUOIDUNG AS ND, SANPHAM AS SP, DONHANG AS DH 
		WHERE SP.IDSP = DH.IDSP AND DH.TENDANGNHAP = ND.TENDANGNHAP AND DH.TRANGTHAIDH = @TENTRANGTHAI

	END
END

GO

CREATE PROC usp_GetProducts2 
AS
BEGIN
		SELECT *, KH.SOLUONGKHO FROM NHOMSP AS N, SANPHAM AS S, KHOHANG AS KH WHERE N.MANHOM = S.MANHOM AND S.IDSP = KH.IDSP 
END

GO

CREATE PROC usp_GetTHONGKE
AS
BEGIN
	SELECT DATEPART(DAY, GETDATE()) AS NGAY, SP.IDSP, SP.TENSP , SP.IMG, SUM(DH.SOLUONGDH) AS SOLUONG, SUM(DH.TONGTIENDH) AS TONGDOANHTHU 
	FROM DONHANG AS DH, SANPHAM AS SP 
	WHERE DATEDIFF(DAY, DH.NGAYDATHANG, GETDATE()) = 0 AND DATEDIFF(MONTH, DH.NGAYDATHANG, GETDATE()) = 0 AND DATEDIFF(YEAR, DH.NGAYDATHANG, GETDATE()) = 0 AND DH.IDSP = SP.IDSP GROUP BY  SP.IDSP, SP.TENSP, SP.IMG
END

GO

CREATE PROC usp_GetLOCDONHANG(@LOC INT)
AS
BEGIN
	IF(@LOC = 1) BEGIN
		SELECT DATEPART(DAY, GETDATE()) AS NGAY, SP.IDSP, SP.TENSP , SP.IMG, SUM(DH.SOLUONGDH) AS SOLUONG, SUM(DH.TONGTIENDH) AS TONGDOANHTHU 
		FROM DONHANG AS DH, SANPHAM AS SP 
		WHERE DATEDIFF(DAY, DH.NGAYDATHANG, GETDATE()) = 0 AND DATEDIFF(MONTH, DH.NGAYDATHANG, GETDATE()) = 0 AND DATEDIFF(YEAR, DH.NGAYDATHANG, GETDATE()) = 0 AND DH.IDSP = SP.IDSP GROUP BY  SP.IDSP, SP.TENSP, SP.IMG
	END ELSE IF(@LOC = 2) BEGIN 
		SELECT DATEPART(MONTH, GETDATE()) AS NGAY, SP.IDSP, SP.TENSP , SP.IMG, SUM(DH.SOLUONGDH) AS SOLUONG, SUM(DH.TONGTIENDH) AS TONGDOANHTHU 
		FROM DONHANG AS DH, SANPHAM AS SP 
		WHERE  DATEDIFF(MONTH, DH.NGAYDATHANG, GETDATE()) = 0 AND DATEDIFF(YEAR, DH.NGAYDATHANG, GETDATE()) = 0 AND DH.IDSP = SP.IDSP GROUP BY  SP.IDSP, SP.TENSP, SP.IMG
	END ELSE BEGIN
		SELECT DATEPART(YEAR, GETDATE()) AS NGAY, SP.IDSP, SP.TENSP , SP.IMG, SUM(DH.SOLUONGDH) AS SOLUONG, SUM(DH.TONGTIENDH) AS TONGDOANHTHU 
		FROM DONHANG AS DH, SANPHAM AS SP 
		WHERE  DATEDIFF(YEAR, DH.NGAYDATHANG, GETDATE()) = 0 AND DH.IDSP = SP.IDSP GROUP BY  SP.IDSP, SP.TENSP, SP.IMG
	END
END

GO

CREATE PROC usp_GetLOC
AS
BEGIN
	SELECT IDLOC, TENLOC FROM LOC ORDER BY IDLOC ASC
END

GO

/*CREATE PROC PROC_THEMKHO(@MASP NVARCHAR(20), @SOLUONGKHO INT, @GIANHAPHANG DECIMAL(18, 0))
AS
BEGIN
	DECLARE @IDSP INT;

	IF EXISTS(SELECT * FROM SANPHAM WHERE MASP = @MASP) BEGIN
	SELECT @IDSP = IDSP FROM SANPHAM WHERE MASP = @MASP
		INSERT KHOHANG (IDSP, SOLUONGKHO, GIANHAPHANG) VALUES (@IDSP, @SOLUONGKHO, @GIANHAPHANG)
	END
END*/

GO

CREATE PROC usp_GetKHOHANG
AS
BEGIN
	SELECT KH.IDKHO, SP.IMG, SP.TENSP, KH.SOLUONGKHO, KH.GIANHAPHANG, SP.GIABAN FROM KHOHANG AS KH, SANPHAM AS SP WHERE KH.IDSP = SP.IDSP
END

GO

CREATE PROC usp_GetKHOHANGUP(@IDKHO INT)
AS
BEGIN
	SELECT SP.IMG, SP.TENSP, KH.SOLUONGKHO, KH.GIANHAPHANG, SP.GIABAN FROM KHOHANG AS KH, SANPHAM AS SP WHERE KH.IDSP = SP.IDSP AND IDKHO = @IDKHO
END

GO

CREATE PROC UPKHOHANG(@IDKHO INT, @SOLUONG INT, @GIANHAP DECIMAL(18, 0))
AS
BEGIN
	 
	IF EXISTS(SELECT * FROM KHOHANG WHERE IDKHO = @IDKHO) BEGIN
		 
		UPDATE KHOHANG SET SOLUONGKHO = @SOLUONG, GIANHAPHANG = @GIANHAP WHERE IDKHO = @IDKHO
	END 
END
